/**
 * API response DTOs — the computed "coaching" outputs served by the backend.
 * Keep these stable; they are the contract the dashboard renders against.
 */

import type { MuscleGroup } from "./domain";

/** Trend classification for a single exercise's recent trajectory. */
export type TrendStatus =
  | "new"
  | "overload"
  | "stagnant"
  | "regression"
  | "plateau";

export interface MetaInfo {
  /** ISO timestamp of when the underlying data was last fetched upstream. */
  fetchedAt: string;
  workoutCount: number;
}

/** Who the dashboard is currently showing — drives the coach-view banner. */
export interface ViewerContextDTO {
  /** Display name of the person whose data is shown. */
  subjectName: string;
  /** True when the signed-in user is viewing someone else's data (coach view). */
  viewing: boolean;
}

/** Headline numbers for the overview page. */
export interface SummaryDTO {
  meta: MetaInfo;
  workoutsThisWeek: number;
  weeklyVolumeKg: number;
  weeklyVolumeChangePct: number | null;
  setsThisWeek: number;
  currentStreakWeeks: number;
  recentPrs: PrEvent[];
}

export interface PrEvent {
  exerciseId: string;
  exerciseName: string;
  date: string; // ISO
  /** Best estimated 1RM achieved, kg. */
  e1rmKg: number;
  /** Change vs previous best, kg. */
  deltaKg: number;
}

export interface ExerciseListItemDTO {
  id: string;
  name: string;
  primaryMuscle: MuscleGroup;
  lastPerformed: string | null; // ISO
  bestE1rmKg: number | null;
  trend: TrendStatus | null;
}

export interface ProgressionPoint {
  date: string; // ISO (workout day)
  e1rmKg: number;
  topSetWeightKg: number | null;
  topSetReps: number | null;
  totalVolumeKg: number;
  isPr: boolean;
}

export interface ExerciseProgressionDTO {
  exerciseId: string;
  exerciseName: string;
  primaryMuscle: MuscleGroup;
  points: ProgressionPoint[];
  trend: TrendStatus | null;
  /** Human-readable evidence note backing the trend, e.g. "+4.2kg e1RM over 6 sessions". */
  trendNote: string | null;
}

/** A time-bucketed volume/load series, plus a per-muscle breakdown. */
export interface VolumePoint {
  /** ISO date of the week start (Monday). */
  weekStart: string;
  totalVolumeKg: number;
  totalSets: number;
  byMuscle: Partial<Record<MuscleGroup, number>>;
}

export interface VolumeDTO {
  meta: MetaInfo;
  weeks: VolumePoint[];
}

export interface MuscleBalanceEntry {
  muscle: MuscleGroup;
  setsLast4Weeks: number;
  sharePct: number;
  daysSinceLastTrained: number | null;
}

export interface BalanceDTO {
  meta: MetaInfo;
  pushPullRatio: number | null;
  muscles: MuscleBalanceEntry[];
}

/**
 * Session-goal classification (inspired by LiftShift): each workout is bucketed
 * by its rep-zone distribution into a primary training emphasis.
 */
export type SessionGoal = "strength" | "hypertrophy" | "endurance" | "mixed";

export interface SessionSummary {
  id: string;
  title: string;
  date: string; // ISO start time
  durationMinutes: number;
  totalVolumeKg: number;
  totalSets: number;
  exerciseCount: number;
  goal: SessionGoal;
  /** Headline muscles trained, most-worked first. */
  topMuscles: MuscleGroup[];
}

export interface HistoryDTO {
  meta: MetaInfo;
  sessions: SessionSummary[];
}

/** Weekly working-set count per muscle — the data behind the muscle heatmap. */
export interface HeatmapCell {
  muscle: MuscleGroup;
  /** Sets per week, oldest → newest, aligned with `weekStarts`. */
  weeklySets: number[];
}

export interface HeatmapDTO {
  meta: MetaInfo;
  /** ISO week-start dates, oldest → newest. */
  weekStarts: string[];
  rows: HeatmapCell[];
}

/** The Claude-powered (or rule-based fallback) coaching analysis card. */
export interface AnalysisDTO {
  /** "ai" when generated by Claude, "rules" for the deterministic fallback. */
  source: "ai" | "rules";
  headline: string;
  bullets: string[];
  generatedAt: string; // ISO
}

export interface ApiError {
  error: string;
  message: string;
}
