import { api } from "../api";
import { useApi } from "../useApi";
import { compactKg, kg, pct, shortDate } from "../format";
import { InsightCard } from "../components/InsightCard";
import { QueryState, StatTile } from "../components/ui";

export function Overview() {
  const summary = useApi("summary", api.summary);
  const analysis = useApi("analysis", api.analysis);

  return (
    <div className="view">
      <div className="view-head">
        <h1>Overview</h1>
        <p className="sub">Where your training stands this week.</p>
      </div>

      <QueryState loading={summary.loading} error={summary.error}>
        {summary.data && (
          <>
            <div className="grid-stats">
              <StatTile label="Workouts this week" value={String(summary.data.workoutsThisWeek)} />
              <StatTile
                label="Weekly volume"
                value={compactKg(summary.data.weeklyVolumeKg)}
                delta={
                  summary.data.weeklyVolumeChangePct != null
                    ? pct(summary.data.weeklyVolumeChangePct)
                    : undefined
                }
                deltaTone={(summary.data.weeklyVolumeChangePct ?? 0) >= 0 ? "pos" : "neg"}
              />
              <StatTile label="Working sets" value={String(summary.data.setsThisWeek)} />
              <StatTile label="Week streak" value={String(summary.data.currentStreakWeeks)} />
            </div>

            <InsightCard title="Coach's read" subtitle="AI-assisted analysis of your recent training">
              {analysis.loading && <p className="muted">Thinking…</p>}
              {!!analysis.error && <p className="muted">Analysis unavailable right now.</p>}
              {analysis.data && (
                <>
                  <p className="ai-headline">{analysis.data.headline}</p>
                  <ul className="ai-bullets">
                    {analysis.data.bullets.map((b, i) => (
                      <li key={i}>{b}</li>
                    ))}
                  </ul>
                  <p className="ai-source">
                    {analysis.data.source === "ai" ? "Generated by Claude" : "Rule-based summary"}
                  </p>
                </>
              )}
            </InsightCard>

            <InsightCard title="Recent personal records" subtitle="New estimated-1RM highs across your lifts">
              {summary.data.recentPrs.length === 0 ? (
                <p className="muted">No recent PRs.</p>
              ) : (
                <ul className="rows">
                  {summary.data.recentPrs.map((pr, i) => (
                    <li key={`${pr.exerciseId}-${i}`}>
                      <div>
                        <div className="session-title">{pr.exerciseName}</div>
                        <div className="session-meta">{shortDate(pr.date)}</div>
                      </div>
                      <div className="session-right tnum">
                        <div>
                          <div className="session-vol">{kg(pr.e1rmKg)}</div>
                          <div className="pos" style={{ fontSize: "0.76rem" }}>
                            +{pr.deltaKg} kg
                          </div>
                        </div>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </InsightCard>
          </>
        )}
      </QueryState>
    </div>
  );
}
